"""Retrieval package boundaries shared by curated evidence workflows."""

from .dual import (
    DualRetrievalResult,
    DualRetriever,
    InMemoryRetrievalStore,
    RecallCase,
    RetrievalDocument,
    RetrievalHit,
    RetrievalNamespace,
    external_document,
    personal_document,
    recall_at_k,
)
from .patient import (
    PatientEvidenceItem,
    PatientEvidenceKind,
    PatientEvidenceQuery,
    PatientEvidenceResponse,
    PatientEvidenceService,
)
from .vector import (
    COLLECTION_SCHEMA,
    DEFAULT_COLLECTION_NAME,
    DEFAULT_MULTILINGUAL_EMBEDDING_MODEL,
    INDEX_VERSION,
    DeterministicHashEmbeddingModel,
    ExternalEvidenceFilters,
    ExternalEvidenceHit,
    ExternalEvidenceMetadata,
    ExternalRecallCase,
    FastEmbedMultilingualModel,
    IndexBuildReport,
    QdrantExternalEvidenceIndex,
    display_citation,
    external_recall_at_k,
    rebuild_qdrant_local,
)
from .bundled import BundledEvidenceCorpus, BundledEvidenceEntry, BundledExternalEvidenceIndex

__all__ = [
    "COLLECTION_SCHEMA",
    "DEFAULT_COLLECTION_NAME",
    "DEFAULT_MULTILINGUAL_EMBEDDING_MODEL",
    "INDEX_VERSION",
    "BundledEvidenceCorpus",
    "BundledEvidenceEntry",
    "BundledExternalEvidenceIndex",
    "DeterministicHashEmbeddingModel",
    "DualRetrievalResult",
    "DualRetriever",
    "ExternalEvidenceFilters",
    "ExternalEvidenceHit",
    "ExternalEvidenceMetadata",
    "ExternalRecallCase",
    "FastEmbedMultilingualModel",
    "InMemoryRetrievalStore",
    "IndexBuildReport",
    "PatientEvidenceItem",
    "PatientEvidenceKind",
    "PatientEvidenceQuery",
    "PatientEvidenceResponse",
    "PatientEvidenceService",
    "QdrantExternalEvidenceIndex",
    "RecallCase",
    "RetrievalDocument",
    "RetrievalHit",
    "RetrievalNamespace",
    "display_citation",
    "external_document",
    "external_recall_at_k",
    "personal_document",
    "rebuild_qdrant_local",
    "recall_at_k",
]
