"""Canonical CarePath domain and persistence contracts."""

from .fhir import FHIR_RESOURCE_TO_MODEL, SUPPORTED_FHIR_RESOURCES
from .models import (
    ActionFeedback,
    AuditEvent,
    CarePlan,
    Goal,
    Interaction,
    InterventionPlan,
    JournalEntry,
    KnowledgeChunk,
    KnowledgeSource,
    Observation,
    PlanAction,
    PlanFeedback,
    UserProfile,
)
from .persistence import (
    ActionFeedbackRecord,
    AuditEventRecord,
    CarePlanRecord,
    GoalRecord,
    InteractionRecord,
    InterventionPlanRecord,
    JournalEntryRecord,
    KnowledgeChunkRecord,
    KnowledgeSourceRecord,
    ObservationRecord,
    PlanActionRecord,
    PlanFeedbackRecord,
    UserProfileRecord,
)

__all__ = [
    "FHIR_RESOURCE_TO_MODEL",
    "SUPPORTED_FHIR_RESOURCES",
    "ActionFeedback",
    "ActionFeedbackRecord",
    "AuditEvent",
    "AuditEventRecord",
    "CarePlan",
    "CarePlanRecord",
    "Goal",
    "GoalRecord",
    "Interaction",
    "InteractionRecord",
    "InterventionPlan",
    "InterventionPlanRecord",
    "JournalEntry",
    "JournalEntryRecord",
    "KnowledgeChunk",
    "KnowledgeChunkRecord",
    "KnowledgeSource",
    "KnowledgeSourceRecord",
    "Observation",
    "ObservationRecord",
    "PlanAction",
    "PlanActionRecord",
    "PlanFeedback",
    "PlanFeedbackRecord",
    "UserProfile",
    "UserProfileRecord",
]
